name: say hello 
on: 
 push:
   branches:
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: print hello
        run: echo "Hello Github Actions" 
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: test the code 
        uses: actions/checkout@v3
      - name: run the command
        run: apt install update -y 
